[package]
name = "revdesk-desktop"
version = "0.0.0"
description = "Revdesk desktop shell"
license = "Apache-2.0"
edition = "2021"

[lib]
name = "revdesk_desktop_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-dialog = "2"
